import express from 'express';
import { countByCity, countByType, createHotel, deleteHotel, findHotel, getHotelRooms, showHotel, updateHotel } from '../controllers/hotel.js';
const router = express.Router();
router.post('/', createHotel);
router.put('/:id', updateHotel);
router.delete('/find/:id', deleteHotel);
router.get('/', showHotel);
router.get('/find/:id', findHotel);
router.get('/countByCity', countByCity);
router.get('/countByType', countByType);
router.get('/room/:id', getHotelRooms);
export default router;